# Namespace deployment
apiVersion: v1
kind: Namespace
metadata:
  name: ${NAMESPACE}
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
    security.openshift.io/scc.podSecurityLabelSync: "false"
    argocd.argoproj.io/managed-by: gitops-${ARGOCD_INSTANCE}
    app.kubernetes.io/part-of: openstack
    app.kubernetes.io/managed-by: kustomize
